name: Deploy Main Infra Resources

on:
  push:
    branches:
      - main
    paths:
      - 'iac/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout
        uses: actions/checkout@v2
    
      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    
      # Deploy Bicep Template
      - name: Deploy Bicep Template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./iac/main.bicep
          parameters: 'buildNumber=m${{ github.run_number }} location=${{ secrets.LOCATION }}'
          failOnStdErr: false
          deploymentMode: 'Incremental'

           